### ISSUE TITLE
Holding CMD+L causes "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by cliffordfajardo** [mupchrch/outline-selection#6]
Selecting hundreds of lines with my mouse cursor works just fine, however when I select multiple lines in the editor using the  `CMD` + `L` shortcut I get an error & sometimes my entire Atom instance Window crashes

![giphy](https://cloud.githubusercontent.com/assets/6743796/16090186/3eb45654-32e3-11e6-8c39-a42e92ca9c8a.gif)

Stack trace error: http://pastebin.com/DgX1imC5

**Comment by mupchrch** [comment]
Thanks for the helpful gif 👍
